name: Build DMA Plugin

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild CE-DMAPlugin.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CE-DMA-Plugin-x64
        path: |
          **/Release/*.dll
          **/Release/*.exe
